# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion1', models.TextField(max_length=50)),
                ('descripcion2', models.TextField(max_length=50)),
                ('descripcion3', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Datos',
                'verbose_name_plural': 'Datos',
            },
        ),
        migrations.RenameField(
            model_name='repuesto',
            old_name='apellido',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='numero_telefonico',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='foto',
            field=models.ImageField(null=True, upload_to=b'pic_folder/'),
        ),
        migrations.AddField(
            model_name='datos',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Repuesto'),
        ),
    ]
