# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170815_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
