# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170817_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='repuesto',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='descripcion1',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='descripcion2',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='descripcion3',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='foto',
            field=models.ImageField(blank=True, upload_to=b'pic_folder/'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Datos',
        ),
    ]
