# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20170821_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=b'pic_folder/'),
        ),
    ]
